<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>SnowFlakeProxy.Tests</RootNamespace>
    <AssemblyName>SnowFlakeProxy.Tests</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\src\ASCOM.SnowFlakeProxy\LocalServer.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ASCOM.SnowFlakeProxy\ASCOM.SnowFlakeProxy.csproj" />
    <Reference Include="ASCOM.Exceptions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=565de7938946fba7, processorArchitecture=MSIL" />
  </ItemGroup>
</Project>
